### ISSUE TITLE
Module 1- Check for Consistency with CANVAS & Proofread Module Page

### ISSUE THREAD

**Issue by joewheaton** [Restoration-USU/Ecohydraulics#18]
@lauren-herbine please have a look at updates I made to 

- [x] [module page](https://restoration-usu.github.io/Ecohydraulics/Modules/Intro.html) 
- [x] [Canvas Module 1 ](https://usu.instructure.com/courses/683598/modules)
See if anything doesn't makes sense or there are broken or incorrect links.

**Comment by lauren-herbine** [comment]
Looking at this and #14, I'll close these tomorrow morning

**Comment by lauren-herbine** [comment]
Everything looks good (links work, makes sense), I corrected 2 minor typos, but am having troubles pushing them (merge conflicts detected). I'll ask you about it when we meet this morning
