### ISSUE TITLE
Please update your office hours.

### ISSUE THREAD

**Issue by joewheaton** [Restoration-USU/Ecohydraulics#2]
@lauren-herbine I added you to [instruction team](https://restoration-usu.github.io/Ecohydraulics/Syllabus/2022_Spring.html#instructors). Please choose and list office hours:

https://github.com/Restoration-USU/Ecohydraulics/blob/0cf2a449c52c3b7b87b6de5b53bcf1c059b5fdcc/Syllabus/2022_Spring.md?plain=1#L90-L94

**Comment by lauren-herbine** [comment]
Oh no, that picture has come back to haunt me
